### ISSUE TITLE
esp and por

### ISSUE THREAD

**Issue by justkaira** [flabser/2next#15]
POR and SPA flags should be added to language choice button

**Comment by medin84** [comment]
предлагаю убрать флаги, поставить макет глобуса.
посмотрел по различным большим сайтам соц.сетей, ни где флаги особо не используются при выборе языка. флаг относится к стране, когда язык не означает страну.
и постоянный поиск бесплатных флагов с одинаковой стилизацией, тоже та еще задачка

**Comment by flabser** [comment]
Хорошо 🆗

**Comment by medin84** [comment]
сделано
только название языка куда делось
```
<availablelangs>
  <value>
    <entry>ON</entry>
    <entry>ENG</entry>
    <entry>ENG</entry>
</value>
```
3-й entry было название

**Comment by flabser** [comment]
Ммм странно.  Посмотрю
