### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by justkaira** [flabser/2next#7]
радиокнопки  Expense Income Transfer , небходимо сделать read-only. Данные значения выставляются в зависимости от выбранной операции

**Comment by medin84** [comment]
по моему делать рид-онли поле делает некоторые не нужные обязательства в использовании.
до пустим в данный момент открыта вьюха переводы, а нужно добавить расход.
получается надо обязательно открывать вьюху расходов, с компа не так сложно, а с мобилы запарно каждый.
можно просто открыть вьюху расходов после сохранения расхода.
